[versions]

kotlin = "1.6.10"
ktor = "1.6.7"
sqlDelight = "2.0.0-alpha03"

[libraries]

ktorServer = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktorNetty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktorKotlinxSerialization = { module = "io.ktor:ktor-serialization", version.ref = "ktor" }
logback = { module = "ch.qos.logback:logback-classic", version = "1.2.5" }
sqlDelightJdbcDriver = { module = "app.cash.sqldelight:jdbc-driver", version.ref = "sqlDelight" }
postgresDriver = { module = "org.postgresql:postgresql", version = "42.3.3" }
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.3.2" }

[bundles]

ktor = ["ktorServer", "ktorNetty", "ktorKotlinxSerialization", "logback"]


[plugins]

kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
sqlDelight = { id = "app.cash.sqldelight", version.ref = "sqlDelight" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }